### PR TITLE
Bugfix : error when reading JEOL .pts file with frame list 

### PR DESCRIPTION
**Pull request by nem1234**
### Description of the change
- Bugfix : error when reading JEOL .pts file with frame list 
- Add test for frame list and frame_start_index
- Add test for frameshift

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [ ] update docstring (if appropriate),
- [ ] update user guide (if appropriate),
- [ ] add an changelog entry in the `upcoming_changes` folder (see [`upcoming_changes/README.rst`](https://github.com/hyperspy/rosettasciio/blob/main/upcoming_changes/README.rst)),
- [ ] Check formatting changelog entry in the `readthedocs` doc build of this PR (link in github checks)
- [x] add tests,
- [ ] ready for review.

### Minimal example of the bug fix or the new feature
```python
import hyperspy.api as hs
s = hs.load("file.pts", frame_list=[1,3])
frame_start_index = s.original_metadata.jeol_pts_frame_start_index
s = hs.load("file.pts", frame_list=[5,2], frame_start_index=frame_start_index)
```

### CODE REVIEW

**Comment by nem1234** [comment]
I'm sorry, I'm now very confused on git merging prosess.
I will reset this and start again from current main branch.

**Comment by jlaehne** [comment]
I also had a mixup when merging upstream not so long ago. Would
```
git fetch upstream
git rebase upstream/main
```
while in this branch fix the commit history?

afterwards you have to force push
```
git push origin +bugfix_jeol_pts_framelist
```

**Comment by nem1234** [comment]
oops, ....
I broke the branch with force push, and can't reopen this.

**Comment by jlaehne** [comment]
OK, I guess a new PR will then be best, no worries.

**Pull request closed without merging**
