### PR TITLE
Release 0.7

### PR DESCRIPTION
**Pull request by CSSFrancis**
### Description of the change
A few sentences and/or a bulleted list to describe and motivate the change:
- [x] Prepare Release using python script
- [x] Add tag to test if package builds correctly
- [ ] Push changes to pypi
- [ ] Make sure conda-forge workflow passes.

### CODE REVIEW

**Review by ericpre — COMMENTED** [review]
Looking at https://github.com/ericpre/rosettasciio/actions/runs/12359210409, the python 3.13 wheels are not built. It would be good to add these by updating accordingly (remove `cp313*`?):
https://github.com/hyperspy/rosettasciio/blob/4e67875f81fd9650b28f7fa80dc21d95c24b8ae5/.github/workflows/release.yml#L26-L27

Sorry this should have been done in https://github.com/hyperspy/rosettasciio/pull/339!

Other than that, this looks good! 😃

**Comment by jlaehne** [comment]
Can we get the small bug-fix in #347 into this release?

**Comment by ericpre** [comment]
Rebased to include https://github.com/hyperspy/rosettasciio/pull/347 and added build of python 3.13 wheels.

**Comment by ericpre** [comment]
The release workflow passes: https://github.com/ericpre/rosettasciio/actions/runs/12415083421

**Comment by ericpre** [comment]
https://pypi.org/project/rosettasciio/0.7/#files

**Comment by jlaehne** [comment]
On the conda feedstock the windows tests are not running through:
https://github.com/conda-forge/rosettasciio-feedstock/pull/11

**Pull request merged**
