### PR TITLE
activate additional queries

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change
The CodeQL scan did not find the errors and warnings currently listed by lgtm.org as noticed in https://github.com/hyperspy/rosettasciio/pull/23#issuecomment-1226322856
Therefore, added [additional queries over the standard ones](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs)

### Progress of the PR
- [x] Change implemented (can be split into several points),
- [x] ready for review.

### CODE REVIEW

**Comment by jlaehne** [comment]
Now it has a lot of additional alerts: https://github.com/hyperspy/rosettasciio/security/code-scanning?query=is%3Aopen+pr%3A28

We might evaluate whether we want both `security-extended` and `security-and-quality` or just the former.

**Comment by jlaehne** [comment]
Merging #23 into this one already closed 318 of the alerts

**Comment by jlaehne** [comment]
Using `BaseException` instead of the sub-class `Exception` may lead to `KeyboardInterrupt` being missed: https://github.com/hyperspy/rosettasciio/security/code-scanning/330
Should we change these occurences as proposed? What is your oppinion @ericpre?

**Comment by jlaehne** [comment]
All other remaining alerts need to be reviewed individually, as some might point to an existing issue, but many will be false alerts or unrelevant.

**Comment by ericpre** [comment]
> Using `BaseException` instead of the sub-class `Exception` may lead to `KeyboardInterrupt` being missed: [Except block handles 'BaseException'](/hyperspy/rosettasciio/security/code-scanning/330) Should we change these occurences as proposed? What is your oppinion @ericpre?

As far as I understand, in most cases, we should use `Exception` to let `KeyboardInterrupt` being raised and use `BaseException` only when we *do want* to catch `KeyboardInterrupt` and do something about it, so they need to be changed.

**Comment by jlaehne** [comment]
> As far as I understand, in most cases, we should use `Exception` to let `KeyboardInterrupt` being raised and use `BaseException` only when we _do want_ to catch `KeyboardInterrupt` and do something about it, so they need to be changed.

Added a commit, I did not find any point where I would have left it as `BaseException`.

**Comment by jlaehne** [comment]
I would propose to merge this PR to have code alert comments for new PRs available. Remaining alerts from the existing code can be addressed in a follow-up PR.

**Review by ericpre — APPROVED** [review]
After merging #59, it now needs a rebase!

**Pull request merged**
